app_name: 'wp-polylex'

quay_registry: 'quay-its.epfl.ch/svc0041'

keybase_secrets: >-
  {{ lookup('pipe',
            'keybase fs read /keybase/team/epfl_wppolylex/ansible_polylex_secrets.yml')
     | from_yaml }}

secrets: '{{ keybase_secrets[inventory_environment] }}'
robot_pull: '{{ keybase_secrets.dockerconfig }}'
