services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: epflsi/polylex:1.7.1
    ports:
      - '80:3000'
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/src
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      METEOR_SETTINGS_FILE: /src/app/meteor-settings.json # See docker/entrypoint.sh

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data: