- name: Polylex ImageStream
  openshift:
    state: latest
    kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      labels:
        app: "{{ polylex_app_name }}"
      name: "{{ polylex_app_name }}"
      namespace: "{{ openshift_namespace }}"

- name: Polylex BuildConfig
  openshift:
    state: latest
    kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      labels:
        app: "{{ polylex_app_name }}"
      name: "{{ polylex_app_name }}"
      namespace: "{{ openshift_namespace }}"
    spec:
      source:
        type: Git
        git:
          uri: https://github.com/epfl-si/wp-polylex
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
      output:
        to:
          kind: ImageStreamTag
          name: "{{polylex_imagestream_name}}:latest"

- name: polylex deploy
  openshift:
    state: latest
    resource: Deployment
    name: "{{ polylex_deploy_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          version: "{{ polylex_image_version }}"
        labels:
          app: "{{ polylex_app_name }}"
          version: "{{ polylex_image_version }}"
        name: "{{ polylex_deploy_name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: "{{ polylex_app_name }}"
        template:
          metadata:
            labels:
              app: "{{ polylex_app_name }}"
              deployment: "{{ polylex_deploy_name }}"
          spec:
            containers:
              - env:
                  - name: MONGO_URL
                    valueFrom:
                       secretKeyRef:
                        name: "{{ polylex_secret_name }}"
                        key: mongo-url
                  - name: PORT
                    value: '3000'
                  - name: ROOT_URL
                    value: 'https://{{ polylex_cname }}'
                  - name: METEOR_SETTINGS
                    valueFrom:
                       secretKeyRef:
                        name: '{{ polylex_secret_name }}'
                        key: meteor-settings
                image: "{{ openshift_image_registry_inside}}/{{ openshift_namespace }}/{{ polylex_imagestream_name }}"
                imagePullPolicy: Always
                name: pod-polylex
                ports:
                  - containerPort: 3000
                    protocol: TCP
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            terminationGracePeriodSeconds: 30
- name: polylex service
  openshift:
    state: latest
    resource: Service
    name: "{{ polylex_svc_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ polylex_svc_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ polylex_app_name }}"
      spec:
        ports:
        - name: "80"
          port: 80
          protocol: TCP
          targetPort: 3000
        selector:
          app: "{{ polylex_app_name }}"
          deployment: "{{ polylex_deploy_name }}"
        type: ClusterIP

- name: polylex route
  openshift:
    state: latest
    resource: Route
    name: "{{ polylex_route_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ polylex_route_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ polylex_app_name }}"
      spec:
        host: "{{ polylex_cname }}"
        port:
          targetPort: "80"
        tls:
          termination: edge
        to:
          kind: Service
          name: "{{ polylex_svc_name }}"
          weight: 100
        wildcardPolicy: None
- name: polylex secrets
  include_tasks: '{{ "secrets.yml" }}'
