- name: Route
  kubernetes.core.k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: '{{ route.host }}'
        namespace: '{{ openshift_namespace }}'
        labels:
          route: '{{ route.availability }}'
        annotations:
          haproxy.router.openshift.io/balance: roundrobin
          haproxy.router.openshift.io/disable_cookies: 'true'
      spec:
        host: '{{ route.host }}'
        wildcardPolicy: None
        port:
          targetPort: '80'
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect
        to:
          kind: Service
          name: '{{ app_name }}'
